### ISSUE TITLE
API for compiler, Or In Memory Compiler

### ISSUE THREAD

**Issue by piyushverma** [jnz/q3vm#30]
Thanks for making such great VM and sharing.

I have a usecase where I want to callAFunction with C Code and get bytecode as result.
Any suggestion what would be easy way to do that ?

There id very good document for VM side but less LCC side.

Thanks

**Comment by SirJson** [comment]
The lack of LCC documentation is what prevented me from the compiler upgrade back then as well.. I think there are some bits around the net but nothing comprehensive.

This might not be the most elegant solution but you could just execute LCC from your Application, collect the result and load that. Embedding LCC could be an licencing issue anyways if my memory serves me right.

**Comment by piyushverma** [comment]
Thanks SirJson,

I try that and noticed LCC is not the only one it usees other executable inside, like q3cp and q3rcc.
You are right, I did not notice for licence, so even linking vm.c & vm.h will have issue.
So looking I need to find some other solution.
