### ISSUE TITLE
vm license

### ISSUE THREAD

**Issue by rofl0r** [jnz/q3vm#31]
is the vm.c code based on q3 sources? if not it should be possible to release it under a less restrictive license like MIT which would make this project a whole lot more useful. the compiler and assembler from q3 could still be kept on GPL license.

**Comment by monological** [comment]
Yes, can you please change the license to MIT.

**Comment by jnz** [comment]
The vm is based on the GPL source code release of Quake 3 Arena, I think I need to stick to that license for this Github project.
